# Generated by Django 4.2.3 on 2023-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_project_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
